version: '{build}'
environment:
  launcherVersion: 3.2.1

init:
- ps: >-
    Get-ChildItem env:

    $commitHash       = "$($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))"

    $env:buildVersion = "$env:launcherVersion-build.$env:APPVEYOR_BUILD_NUMBER"

    $env:nugetVersion = "$env:launcherVersion-beta.$env:APPVEYOR_BUILD_NUMBER"
    
    Update-AppveyorBuild -Version $env:buildVersion

pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: true
  file: SolutionAssemblyInfo.cs
  assembly_version: $(launcherVersion)
  assembly_file_version: $(launcherVersion)
  assembly_informational_version: $(launcherVersion)
dotnet_csproj:
  patch: true
  file: 'Flow.*\*.csproj'
  version: $(launcherVersion)
  package_version: $(nugetVersion)
  assembly_version: $(launcherVersion)
  file_version: $(launcherVersion)
  informational_version: $(launcherVersion)

skip_commits:
  files:
    - '*.md'

image: Visual Studio 2019
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  project: Flow.Launcher.sln
  verbosity: quiet

artifacts:
- path: 'Output\Packages\*'
- path: 'Output\Release\Flow.Launcher.Plugin.*.nupkg'
  name: Plugin nupkg
- path: 'Output\Release\Flow.Launcher.Plugin.*.snupkg'
  name: Plugin snupkg